### ISSUE TITLE
Can't persuade lua to release memory using moonfltk and oocairo - probably my incompetence rather than a bug.

### ISSUE THREAD

**Issue by bogbasic** [stetre/moonfltk#23]
I have some code [here](https://www.pastery.net/yjwatr/) which uses oocairo to draw a probability tree and then draw some paths through it which are displayed in 'real time' in an FLTK box. The problem is that when I run it, the memory used by lua goes up and up and never gets released till I kill the gui or the computer crashes. I assume that the problem lies in this bit: 
```
surface:write_to_png("simple-example.png") --some cairo stuff
png=fl.png_image("simple-example.png") --read the image into a box widget
box:image(png)
box:redraw()
fl:check()
png:uncache()
```
but I am not sure. The png:uncache() helps a lot to keep the memory used by Xorg down a lot. I tried using local variables rather than globals and followed the advice in the documentation and in the progress bar example file, which suggest doing something like this: 
```
w:remove(progress) -- remove progress bar from window
-- unreference the progress bar, so that it will be GC'ed
fl.unreference(progress)
-- let's force GC:
progress = nil
collectgarbage()
```
but without success. As per title, this is almost certainly my incompetence rather than a bug, but you kindly requested on the /r/lua forum that I should post something here. If its not my numpty code, I fear that the problem might be in oocairo??

**Comment by stetre** [comment]
I think your assumption is correct, because by repeatedly running that code you continuously create png_image objects that are never released.

What you should do is to get the old box:image (if any) before setting a new one, and unreference it, so that when the garbage collector runs it gets deleted. That is:

    surface:write_to_png("simple-example.png") --some cairo stuff
    png=fl.png_image("simple-example.png") --read the image into a box widget
    --------------------------------------------------------
    -- Get and unreference the old image:
    local oldpng = box:image()
    if oldpng then fl.unreference(oldpng) end
    -- Run the gc (this is not really needed: if the gc is enabled, it will however run by itself sooner or later):
    oldpng = nil -- so that it is gc'ed
    collectgarbage()
    --------------------------------------------------------
    box:image(png)
    box:redraw()
    fl:check()
    png:uncache()

This should work. Hope I got it right, because it's been a while since I last tinkered with FLTK. Let me know!

**Comment by stetre** [comment]
As I said, I'm a bit rusty... The above code is wrong. The old image must be deleted after setting the new one, so:

    surface:write_to_png("simple-example.png") --some cairo stuff
    png=fl.png_image("simple-example.png") --read the image into a box widget
    --------------------------------------------------------
    -- Get the old image:
    local oldpng = box:image()
    -- Set the new image:
    box:image(png)
    -- Unreference the old image, if any:
    if oldpng then
       fl.unreference(oldpng)
       oldpng = nil -- so that it is gc'ed
       collectgarbage()
    end
    --------------------------------------------------------
    box:redraw()
    fl:check()
    png:uncache()

**Comment by bogbasic** [comment]
Very clever - it works perfectly. Amazing, thanks!! I have learnt a lot from this. Maybe a mention in the manual would be good. You actually don't need the png:uncache() with your code.

**Comment by stetre** [comment]
You're welcome.

The manual actually already mentions it in the "Unreferencing objects" section: _"There may be, however, situations when you want objects to be collected before than that. For example if you dynamically create lots of them for temporary use only."_

**Comment by bogbasic** [comment]
Sorry Stefan

Thank you, I did read that many times ;-0 but the way you assigned oldpng, etc, before unreferencing it was well beyond me. 

Cheers again. Jon.C.
