### ISSUE TITLE
$ make LUAVER=5.4

### ISSUE THREAD

**Issue by atan2005** [stetre/moonfltk#25]
g++ -O2 -Wall -Wextra -DCOMPAT53_PREFIX=moonfltk_compat_ -DLUAVER=5.4 -DUSE_GL=1 -DUSE_IMAGES=1  -DMINGW -Wno-unused-parameter -Wno-long-long  -I/mingw64/include -march=x86-64 -mtune=generic -O2 -pipe -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -c -o handlers.o handlers.cc
handlers.cc: In function 'int Add_fd(lua_State*)':
handlers.cc:242:26: error: invalid conversion from 'void (*)(int, void*)' to 'Fl_FD_Handler' {aka 'void (*)(long long unsigned int, void*)'} [-fpermissive]
  242 |     Fl::add_fd(fd, when, FdHandler, (void*)0);
      |                          ^~~~~~~~~
      |                          |
      |                          void (*)(int, void*)
In file included from internal.h:47,
                 from handlers.cc:26:
C:/msys64/mingw64/include/FL/Fl.H:463:54: note:   initializing argument 3 of 'static void Fl::add_fd(int, int, Fl_FD_Handler, void*)'
  463 |   static void add_fd(int fd, int when, Fl_FD_Handler cb, void* = 0); // platform dependent
      |                                        ~~~~~~~~~~~~~~^~
make[1]: *** [<builtin>: handlers.o] Error 1
make[1]: Leaving directory '/home/61401/moonfltk/src'
make: *** [Makefile:5: build] Error 2

**Comment by stetre** [comment]
Thank you. It should be fixed now, but let me know if it works because I don't have a Windows installation at hand to try it out.

**Comment by atan2005** [comment]
I have downloaded handlers.cc file, build and install without any errors. I have also tested moonfltk.dll against corresponding examples\*.lua and it is working fine. Fltk is indeed very fast comparing against Freeglut and Glfw.
